### ISSUE TITLE
Tests failing on Windows

### ISSUE THREAD

**Issue by h3xstream** [socketry/multipart-post#51]
After running `parts_spec.rb`, I get those two tests failing.

**test_multibyte_file_length**
```ruby
expected: == 187
     got:    186
./spec/parts_spec.rb:34:in `assert_part_length'
./spec/parts_spec.rb:76:in `block (2 levels) in <top (required)>'
```

**test_multibyte_filename**
```ruby
Errno::EINVAL: Invalid argument @ rb_sysopen - C:/Users/parteau/AppData/Local/Temp/ファイル
20170803-137124-14setfh
./spec/parts_spec.rb:81:in `new'
./spec/parts_spec.rb:81:in `block (2 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'
```

OS : Windows Version 10.0.14393
Ruby : ruby 2.3.0p0

**Comment by ioquatix** [comment]
We now have GitHub Actions, so in theory can support Windows testing. Care to submit a PR?
